

import { motion } from "framer-motion";
import { Link } from "react-router-dom";
const TermAndConditions = () => {
    return (
        <section className="bg-gray-50 px-6 md:px-16 py-40">

            <motion.h1
                className="text-3xl md:text-5xl font-extrabold text-center text-gray-900 mb-6 tracking-wide"
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
            >
                Terms & Conditions
            </motion.h1>

            <p className="text-sm text-gray-500 text-center mb-4">
                📅 Last modified: <span className="font-medium">16.09.2025</span>
            </p>

            <div className="max-w-5xl mx-auto p-6 md:p-5">
                <article
                    className="prose prose-gray prose-sm md:prose-base lg:prose-lg max-w-none 
          prose-headings:font-semibold prose-headings:text-gray-900 
          prose-p:text-gray-700 prose-li:marker:text-indigo-500"
                >
                    <p>
                        This document (“Terms”) is an electronic record in terms of Information
                        Technology Act, 2000 and rules thereunder, and other applicable law and
                        is generated by a computer system and does not require any physical or
                        digital signatures.
                    </p>
                    <br></br>
                    <p>
                        Parties are responsible for ensuring that any “Personal Data” (as defined
                        in the Act) it supplies to the Company has been collected within the terms
                        of the Information Technology (Reasonable security practices and
                        procedures and sensitive personal data or information) Rules, 2011.
                    </p><br></br>
                    <p>
                        The Company agrees to process the data in accordance with lawful and
                        reasonable written instructions provided by the parties of this Platform.
                    </p><br></br>

                    <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-3">1. Applicability</h2>
                    <p>
                        The Company, Kokum Assist LLP ("Company" or "We"), with a registered
                        address at 601 Gopal Vishnu CHS Ltd, Mahant Road, Opposite Ruia School,
                        Vile Parle (East), Mumbai-400057, Maharashtra, India operates under the
                        brand name Spectrable and provides a distinct feature with the Spectrable
                        AI Chatbot for better healthcare management.
                    </p><br></br>
                    <p>
                        These Terms and Conditions apply to the Spectrable platform and its
                        features. By accessing or using it, whether as a “Caretaker” or as a
                        “Therapist”, you agree to be bound by these Terms.
                    </p><br></br>

                    <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-3">2. Introduction</h2>
                    <p>
                        These terms and conditions (“Terms”) govern the use of services made
                        available on or through the Spectrable website and/or app (collectively,
                        the “Platform”, and together with the services made available on or
                        through the Platform, the “Services”).
                    </p><br></br>
                    <p>
                        These Terms also include our privacy policy, available at <Link to="/privacy-policy">[https://spectr-able-corazor.onrender.com/privacy-policy]</Link>,
                        which forms an essential part of these Terms. By accessing and using the
                        Services, you accept these Terms and Conditions.
                    </p>
                    <br></br>
                    <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-3">3. Purpose and Understanding</h2>
                    <p>
                        These Conditions shall apply as between the Company and the Therapists
                        and also between the Caretakers and Therapists...
                    </p><br></br>

                    <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-3">4. Eligibility and Use of Services</h2>
                    <p>
                        Persons who are "incompetent to contract" within the meaning of the
                        Indian Contract Act, 1872, are not eligible to use the Platform...
                    </p>
                    <br></br>
                    <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-3">19. Disclaimer</h2>
                    <p>
                        The Platform, including its AI-generated outputs, is intended solely as
                        an assistive digital tool for caregivers, therapists, and clients. It is
                        not classified as a medical device...
                    </p>
                    <br></br>
                    <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-3">Glossary</h2><br></br>
                    <ul>
                        <li>
                            <strong>Company, We, Us, or Our</strong> refers to Kokum Assist LLP...
                        </li>
                        <li>
                            <strong>Platform</strong> means the Company’s mobile application,
                            website and/or app, software...
                        </li>
                        <li>
                            <strong>Therapist</strong> means a licensed or qualified healthcare
                            professional...
                        </li>
                    </ul>
                </article>
            </div>
        </section>
    );
};

export default TermAndConditions;
